hydra:
  run:
    dir: './outputs/${task_name}/${now:%Y-%m-%d_%H-%M-%S}'

task_name: 'esm2_t33_650M_UR50D_ProtST'

# path
data_path: './database'
output_path: './outputs/${task_name}/${now:%Y-%m-%d_%H-%M-%S}'

# model
protein_model_name: '/root/model/esm2_t33_650M_UR50D'
protein_model_fixed: False
text_model_name: '/root/model/BiomedNLP-PubMedBERT-base-uncased-abstract'
text_model_fixed: True
projection_dim: 512
fusion_num_heads: 8
fusion_num_layers: 1
fusion_batch_norm: True
mlp_num_layers: 2
mlm_probability: 0.15



# dataset
dataset: 'Swissprot_Protst'
max_length: 1022

# train
lr: 1e-5
lr_ratio: 0.1
fp16: True
batch_size: 3
num_epochs: 35
weight_decay: 0.0
warmup_ratio: 0.03

# eval
metric_for_best_model: 'loss'

# task
task: 'ProtSTPretrainTask'